#!/bin/sh
#
# Starts openbox
#

BIN=/usr/bin/openbox

export DISPLAY=:0.0

start() {
	printf "Starting openbox: "
	openbox &
	xterm &
}

stop() {
	printf "Stopping openbox: "
	killall openbox
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
